name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : download netsdk installer
      run : |
        wget https://aka.ms/dotnet/net6/dev/Sdk/dotnet-sdk-win-x64.exe
 
