name: download vagrant

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_CEF_BUILD_TOKEN }}
     
      - name: download and commit to repo
        run: |
          echo 'downloading'
          wget https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.msi
          git config --global user.name 'pedoc'
          git config --global user.email 'pedoc@qq.com'
          git add -A
          git commit -am "Automated commit"
          git push
