name: download netcore sdk 6 windows installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_CEF_BUILD_TOKEN }}
     
      - name: download and commit to repo
        run: |
          echo 'downloading'
          wget https://aka.ms/dotnet/net6/dev/Sdk/dotnet-sdk-win-x64.exe
          git config --global user.name 'pedoc'
          git config --global user.email 'pedoc@qq.com'
          git add -A
          git commit -am "Automated commit"
          git push
